vms:
  - name: node01.cluster.local
    ip: "192.168.50.101"
    cpu: 5
    memory: 16384
    secondary_disks: 1
  - name: node02.cluster.local
    ip: "192.168.50.102"
    cpu: 5
    memory: 16384
    secondary_disks: 3
  - name: node03.cluster.local
    ip: "192.168.50.103"
    cpu: 5
    memory: 16384
    secondary_disks: 1
  - name: edge.cluster.local
    ip: "192.168.50.199"
    cpu: 3
    memory: 16384
    secondary_disks: 1
  - name: node04.cluster.local  # Nouvelle VM 1
    ip: "192.168.50.104"
    cpu: 5
    memory: 4096
    secondary_disks: 1
  - name: node05.cluster.local  # Nouvelle VM 2
    ip: "192.168.50.105"
    cpu: 5
    memory: 4096
    secondary_disks: 1  

disk_size: 50000
disks_folder_path: /dev/sdh







