# Installation des services MapR sur les noeuds appropriés selon leur rôle

- name: Installer des services MapR sur les noeuds appropriés
  package:
    name: "{{ item.pkg }}"  # Nom du package à installer
    state: present  # Assurer que le package est présent
  loop:
    - { pkg: 'mapr-zookeeper', condition: "'ZooKeeper_nodes' in group_names" }  # Zookeeper
    - { pkg: 'mapr-cldb', condition: "'CLDB_nodes' in group_names" }  # CLDB
    - { pkg: 'mapr-resourcemanager', condition: "'ResourceManager_nodes' in group_names" }  # Resource Manager
    - { pkg: 'mapr-fileserver', condition: "'FileServer_nodes' in group_names" }  # File Server
    - { pkg: 'mapr-nfs', condition: "'NFS_nodes' in group_names" }  # NFS
    - { pkg: 'mapr-nodemanager', condition: "'NodeManager_nodes' in group_names" }  # Node Manager
    - { pkg: 'mapr-historyserver', condition: "'HistoryServer_nodes' in group_names" }  # History Server
    - { pkg: 'mapr-webserver', condition: "'WebServer_nodes' in group_names" }  # Web Server
    - { pkg: 'mapr-apiserver', condition: "'ApiServer_nodes' in group_names" }  # API Server
    - { pkg: 'mapr-timelineserver', condition: "'TimelineServer_nodes' in group_names" }  # Timeline Server
    - { pkg: 'mapr-hue', condition: "'Hue_nodes' in group_names" }  # Hue
    - { pkg: 'mapr-drill', condition: "'Drill_nodes' in group_names" }  # Drill
    - { pkg: 'mapr-hive', condition: "'Hive_nodes' in group_names" }  # Hive
    - { pkg: 'mapr-hivemetastore', condition: "'Hive_nodes' in group_names" }  # Hive Metastore
    - { pkg: 'mapr-hiveserver2', condition: "'Hive_nodes' in group_names" }  # Hive Server 2
    - { pkg: 'mapr-opentsdb', condition: "'OpenTSDB_nodes' in group_names" }  # OpenTSDB
    - { pkg: 'mapr-collectd', condition: "'CollecTD_nodes' in group_names" }  # Collectd
    - { pkg: 'mapr-gateway', condition: "'Gateway_nodes' in group_names" }  # Gateway
    - { pkg: 'mapr-httpfs', condition: "'HttpFS_nodes' in group_names" }  # HTTPFS
  when: "{{ item.condition }}"  # Exécute la tâche seulement si la condition est remplie
